name: xero/ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        go: [ '1.22.x' ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@main

      # Setup our base Go environment ğŸ§¬
      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      # Install Go Staticcheck
      - name: Install Go Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      # Install Go Critic
      - name: Install Go Critic
        run: go install -v github.com/go-critic/go-critic/cmd/gocritic@latest
      
      # Run Go Lint
      - name: Go Lint ğŸ§¹
        run: make lint

      # Run Go Vet
      - name: Go Vet ğŸ¶
        run: make vet

      # Run Go Fmt
      - name: Go Fmt ğŸ“
        run: make format

      # Run Go Critic
      - name: Go Critic ğŸ•µï¸
        run: make critic